from dotenv import load_dotenv
import os

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "./.env"))

FIREBASE_PROJECT_ID = os.getenv("AGENT_FIREBASE_PROJECT_ID")
FIREBASE_PRIVATE_KEY = os.getenv("AGENT_FIREBASE_PRIVATE_KEY").replace("\\n", "\n")
FIREBASE_CLIENT_EMAIL = os.getenv("AGENT_FIREBASE_CLIENT_EMAIL")
FIREBASE_TOKEN_URI = os.getenv("AGENT_FIREBASE_TOKEN_URI")
FIREBASE_API_KEY = os.getenv("AGENT_FIREBASE_API_KEY")
LIQUIDITY_POOL_SERVER_URL = os.getenv("LIQUIDITY_POOL_SERVER_URL", "")
FIREBASE_SERVER_ENDPOINT = os.getenv("FB_SERVER_ENDPOINT")
COINMARKETCAP_API_KEY = os.getenv("COINMARKETCAP_API_KEY")
MORALIS_API_KEY = os.getenv("MORALIS_API_KEY")
ENSO_API_KEY = os.getenv("ENSO_API_KEY")
SERPER_API_KEY = os.getenv("SERPER_API_KEY")
SOL_VALIDATORS_API_KEY = os.getenv("SOL_VALIDATORS_API_KEY")
LULO_API_KEY = os.getenv("LULO_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TWITTER_BEARER_TOKEN = os.getenv("TWITTER_BEARER_TOKEN", "")
SOLANA_RPC = os.getenv("SOLANA_RPC")
