name: Python Unit Tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./py-server/functions
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run tests for solana_yield_agent
        working-directory: ./py-server/functions
        run: |
          pytest tests/agents/solana_yield_agent/ -v --tb=short

      - name: Run tests for liquidation_agent
        working-directory: ./py-server/functions
        run: |
          pytest tests/agents/liquidation_agent/ -v --tb=short

      - name: Run tests for dex_agent
        working-directory: ./py-server/functions
        run: |
          pytest tests/agents/dex_agent/ -v --tb=short

      - name: Run tests for automated_memecoin_trader
        working-directory: ./py-server/functions
        run: |
          pytest tests/agents/automated_memecoin_trader/ -v --tb=short

      - name: Run tests for unified_transfer
        working-directory: ./py-server/functions
        run: |
          pytest tests/agents/unified_transfer/ -v --tb=short

      - name: Test summary
        if: always()
        run: |
          echo "Tests completados para el commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
